export const REQUESTING_NOWPLAYING_MOVIES = 'REQUESTING_NOWPLAYING_MOVIES';
export const REQUEST_NOWPLAYING_MOVIES_SUCCESS =
  'REQUEST_NOWPLAYING_MOVIES_SUCCESS';
export const REQUEST_NOWPLAYING_MOVIES_FAILED =
  'REQUEST_NOWPLAYING_MOVIES_FAILED';
