export const REQUESTING_POPULAR_MOVIES = 'REQUESTING_POPULAR_MOVIES';
export const REQUEST_POPULAR_MOVIES_SUCCESS = 'REQUEST_POPULAR_MOVIES_SUCCESS';
export const REQUEST_POPULAR_MOVIES_FAILED = 'REQUEST_POPULAR_MOVIES_FAILED';
