export const REQUESTING_POPULAR_TVSHOW = 'REQUESTING_POPULAR_TVSHOW';
export const REQUEST_POPULAR_TVSHOW_SUCCESS = 'REQUEST_POPULAR_TVSHOW_SUCCESS';
export const REQUEST_POPULAR_TVSHOW_FAILED = 'REQUEST_POPULAR_TVSHOW_FAILED';
