export const REQUESTING_TOP_RATED_MOVIES = 'REQUESTING_TOP_RATED_MOVIES';
export const REQUEST_TOP_RATED_MOVIES_SUCCESS =
  'REQUEST_TOP_RATED_MOVIES_SUCCESS';
export const REQUEST_TOP_RATED_MOVIES_FAILED =
  'REQUEST_TOP_RATED_MOVIES_FAILED';
