export const REQUESTING_TOP_RATED_TVSHOW = 'REQUESTING_TOP_RATED_TVSHOW';
export const REQUEST_TOP_RATED_TVSHOW_SUCCESS =
  'REQUEST_TOP_RATED_TVSHOW_SUCCESS';
export const REQUEST_TOP_RATED_TVSHOW_FAILED =
  'REQUEST_TOP_RATED_TVSHOW_FAILED';
