export const REQUESTING_UPCOMING_MOVIES = 'REQUESTING_UPCOMING_MOVIES';
export const REQUEST_UPCOMING_MOVIES_SUCCESS =
  'REQUEST_UPCOMING_MOVIES_SUCCESS';
export const REQUEST_UPCOMING_MOVIES_FAILED = 'REQUEST_UPCOMING_MOVIES_FAILED';
